export default function carsGenerator(count) {
  const res = [
    {id:0, src: 'idImg_000', info:'avant,escalier'},
    {id:1, src: 'idImg_000', info:'arriere,escalier'},
    {id:2, src: 'idImg_000', info:'arrieve,pave,contour de piscine'},
    {id:3, src: 'idImg_000', info:'avant,escalier'},
    {id:4, src: 'idImg_000', info:'arriere,escalier'},
    {id:5, src: 'idImg_000', info:'arrieve,pave,contour de piscine'},
    {id:6, src: 'idImg_000', info:'avant,escalier'},
    {id:7, src: 'idImg_000', info:'arriere,escalier'},
    {id:8, src: 'idImg_000', info:'arrieve,pave,contour de piscine'},
    {id:9, src: 'idImg_000', info:'avant,escalier'},
    {id:10, src: 'idImg_000', info:'arriere,escalier'},
    {id:12, src: 'idImg_000', info:'arrieve,pave,contour de piscine'},
    {id:11, src: 'idImg_000', info:'avant,escalier'},
    {id:12, src: 'idImg_000', info:'arriere,escalier'},
    {id:13, src: 'idImg_000', info:'arrieve,pave,contour de piscine'},
    // {id:3, src: './img/idImg_003.jpg', info:'arrieve,pave'},
    // {id:4, src: './img/idImg_004.jpg', info:'arrieve,contour de piscine'},
    // {id:5, src: './img/idImg_005.jpg', info:'avant,fleur,escalier'},
    // {id:6, src: './img/idImg_006.jpg', info:'avant,escalier'},
    // {id:7, src: './img/idImg_007.jpg', info:'avant,fleur'},
    // {id:9, src: './img/idImg_008.jpg', info:'avant,fleur'},
    // {id:10, src: './img/idImg_000.jpg', info:'avant,escalier'},
    // {id:11, src: './img/idImg_001.jpg', info:'arriere,escalier'},
    // {id:12, src: './img/idImg_002.jpg', info:'arrieve,pave,contour de piscine'},
    // {id:13, src: './img/idImg_003.jpg', info:'arrieve,pave'},
    // {id:14, src: './img/idImg_004.jpg', info:'arrieve,contour de piscine'},
    // {id:15, src: './img/idImg_005.jpg', info:'avant,fleur,escalier'},
    // {id:16, src: './img/idImg_006.jpg', info:'avant,escalier'},
    // {id:17, src: './img/idImg_007.jpg', info:'avant,fleur'},
    //{id:18, src: './img/idImg_008.jpg', info:'avant,fleur'},

]
  return res
}